# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://snowdayclub.github.io'
baseurl: ''
title: 'Snowday Club'
description: 'Snowday Club'
permalink: pretty
logo: "/assets/logos/logo@32px.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/
- title: Categories
  url: /categories/
- title: About
  url: /about/

# Footer nav
navigation_footer:
- title: Based on Alembic theme
  url: "https://github.com/daviddarnes/alembic"

social_links:
  GitHub: https://github.com/snowdayclub

# Collections
collections:
  posts:
    title: Posts
    output: true
    #description: "My thoughts and ideas"
    #feature_text: |
    #  Welcome to my blog
    #feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
